---
driver:
  name: ec2
  aws_ssh_key_id: tools-team
  region: us-west-2
  subnet_id: subnet-2a251342
  instance_type: t2.micro
  tags:
    Name: delivery-sugar-kitchen

provisioner:
  name: chef_zero

transport:
  ssh_key: 
  username: ubuntu

platforms:
  - name: ubuntu-12.04-12.6.0
    driver:
      image_id: ami-5ff8e96f
    driver_config:
      provision: true
      require_chef_omnibus: 12.6.0
  - name: ubuntu-12.04-latest
    driver:
      image_id: ami-5ff8e96f
    driver_config:
      provision: true
      require_chef_omnibus: latest

suites:
  - name: default
    run_list:
      - recipe[default_cookbook::default]
    attributes:
